# DataSource settings
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    url: jdbc:postgresql://localhost:5432/postgres
    password: pass
  # Hibernate settings
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql

  flyway:
    baseline-on-migrate: true
    enable: true
    user: postgres
    password: pass
    baseline-description: "init"
    baseline-version: 0

# JWT Properties
jwt:
  secret: 8DKXq6XNr6o+ePpNay+V1nvNyaF6Rumj
  expiration-time: 86400000 # 1 day in milliseconds
  token-prefix: Bearer
  header-string: Authorization

# Logging SQL queries
#logging:
#  level:
#    org:
#      springframework: DEBUG

# Server port (you can change it to your desired port)
server:
  port: 8080
