# application.yml
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    url: jdbc:postgresql://localhost:5432/postgres
    password: pass

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql

  flyway:
    baseline-on-migrate: true
    enable: true
    user: postgres
    password: pass
    baseline-description: "init"
    baseline-version: 0

jwt:
  secret: 8DKXq6XNr6o+ePpNay+V1nvNyaF6Rumj
  expiration-time: 86400000
  token-prefix: Bearer
  header-string: Authorization

server:
  port: 8080

currency:
  api:
    key: cur_live_nrIl31BQlFn4J9AXmbz2p6vMau5ZeuySaV9p7AjZ
